services:
  db:
    image: postgres:17
    container_name: news-sheet-db
    restart: no
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    image: news-sheet_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-sheet-backend
    restart: no
    depends_on:
      db:
        condition: service_healthy
    environment:
      RUN__HOST: 0.0.0.0
      RUN__PORT: 8000
      DB__ASYNC_URL: ${DB_ASYNC_URL}
      DB__SYNC_URL: ${DB_SYNC_URL}
      DB__ECHO: "true"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    working_dir: /app/app
    entrypoint: ["/app/entrypoints/backend-entrypoint.sh"]

  scheduler:
    image: news-sheet_scheduler
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-sheet-scheduler
    restart: no
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB__ASYNC_URL: ${DB_ASYNC_URL}
      DB__SYNC_URL: ${DB_SYNC_URL}
      PYTHONPATH: /app/app
    volumes:
      - ./backend:/app
    working_dir: /app/app
    entrypoint: ["/app/entrypoints/scheduler-entrypoint.sh"]
  frontend:
    image: news-sheet_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news-sheet-frontend
    restart: no
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    working_dir: /app

volumes:
  db_data:
  frontend_node_modules:
