"""init

Revision ID: 56f952c2c02f
Revises: 9bf9c7ad6783
Create Date: 2026-03-02 11:24:57.390178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f952c2c02f'
down_revision: Union[str, Sequence[str], None] = '9bf9c7ad6783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date', sa.String(length=40), nullable=False))
    op.drop_index(op.f('ix_incidents_date_raw'), table_name='incidents')
    op.create_index(op.f('ix_incidents_date'), 'incidents', ['date'], unique=False)
    op.drop_column('incidents', 'date_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date_raw', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_incidents_date'), table_name='incidents')
    op.create_index(op.f('ix_incidents_date_raw'), 'incidents', ['date_raw'], unique=False)
    op.drop_column('incidents', 'date')
    # ### end Alembic commands ###
