"""init

Revision ID: 702697425b93
Revises: 8b6bd4d9985f
Create Date: 2026-03-03 04:27:56.130900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '702697425b93'
down_revision: Union[str, Sequence[str], None] = '8b6bd4d9985f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'date',
                    existing_type=sa.VARCHAR(length=50),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    postgresql_using='"date"::timestamptz'
                    # ### end Alembic commands ###
                    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'date',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.VARCHAR(length=50),
                    existing_nullable=False,
                    postgresql_using='"date"::timestamptz'
                    # ### end Alembic commands ###
                    )
