"""init

Revision ID: 9bf9c7ad6783
Revises: b33c1908c575
Create Date: 2026-03-02 11:24:08.683670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bf9c7ad6783'
down_revision: Union[str, Sequence[str], None] = 'b33c1908c575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date_raw', sa.String(length=40), nullable=False))
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incidents', 'images',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('incidents', 'categories',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_incidents_date'), table_name='incidents')
    op.create_index(op.f('ix_incidents_date_raw'), 'incidents', ['date_raw'], unique=False)
    op.drop_column('incidents', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_incidents_date_raw'), table_name='incidents')
    op.create_index(op.f('ix_incidents_date'), 'incidents', ['date'], unique=False)
    op.alter_column('incidents', 'categories',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('incidents', 'images',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('incidents', 'date_raw')
    # ### end Alembic commands ###
