"""init

Revision ID: d7bb3f411b45
Revises: 
Create Date: 2026-02-27 03:35:45.399403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7bb3f411b45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date_raw', sa.String(length=40), nullable=False))
    op.add_column('incidents', sa.Column('date_ts', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incidents', 'images',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('incidents', 'categories',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('ix_incidents_date'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_link'), table_name='incidents')
    op.create_index(op.f('ix_incidents_date_raw'), 'incidents', ['date_raw'], unique=False)
    op.create_index(op.f('ix_incidents_date_ts'), 'incidents', ['date_ts'], unique=False)
    op.create_unique_constraint(None, 'incidents', ['link'])
    op.drop_column('incidents', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'incidents', type_='unique')
    op.drop_index(op.f('ix_incidents_date_ts'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_date_raw'), table_name='incidents')
    op.create_index(op.f('ix_incidents_link'), 'incidents', ['link'], unique=True)
    op.create_index(op.f('ix_incidents_date'), 'incidents', ['date'], unique=False)
    op.alter_column('incidents', 'categories',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('incidents', 'images',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('incidents', 'date_ts')
    op.drop_column('incidents', 'date_raw')
    # ### end Alembic commands ###
